apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:zlTHnS9H/X3jhtPpGQ+UlZbcm3MXdNBrnTUQw3aKpDwp9KsLN9BrXw==,iv:0UYUSena3D4dc+ncuJigAYx/DRA0FpdlhupALfAT2PA=,tag:YyamSaTX+c5LY05zgdp/vg==,type:str]
sops:
  age:
    - recipient: age15junp5n3mp3cwtg3kwxz7azea56936aewx4uyjaqlk38dvaq6y5s5r8lr9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MzRibjB4Y2l3SzlTL0pL
        WkNub1JibWMwamc0RmZBUFhaQ2M5UGR2b0ZrCmNDRHVhWXhPN04rRE85UFBzM0RT
        YVZ2NTllU2U5MEMrMGtRWDRjTUk4cWcKLS0tIHlxM1dEeERuVmhVSlFOcTE4Zm9t
        LzRwaE5ON0R4K0Q1bXUramllQmFaSG8Kx3XgKAfaQdPR22fzwAOQTWgfaAFgSSPV
        Qann4WFVs+9wUl15oG2S3JAeyD/7SeIigVoXf3EoPs4/uMJ3oj/XDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T20:52:08Z"
  mac: ENC[AES256_GCM,data:GP72TKS0uEmC3sabtb7RmtpOhXGvtvKbE29y4h3KfDj8pIeeSmAvh1TAaGLW0XsHzDT1JujjVBYhUhUrYmvgzdRHT4ngEcfVJzUhb36axMke/etYOhGr7OE/q1Q45ZsMKvONenGNl7xWiJoPFG3hb8mKM8zAalro+yUHE5H9n6g=,iv:lenm+WpYOqMZQ57gVfpKZunwTB8E3dQn9DFyUonr/w0=,tag:i5pJg2sDwXiyGJCFNs/3Jg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
