apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:7wzUZdcfnhaV6P8=,iv:5/fDWm2eMuvzUjiljLPiQoMqWTEZoXwAMAZ8n0NJHGk=,tag:Efb0emxh8HMBO5lGRO4log==,type:str]
sops:
  age:
    - recipient: age15junp5n3mp3cwtg3kwxz7azea56936aewx4uyjaqlk38dvaq6y5s5r8lr9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRGUwMjlSVEYvUnd3aXdY
        WXBSRjE4dXl3TkFTSGJDNDMyR3JhZVpmMWpNCmR2enNWcFZIOXdCeUM5cUZwVkZ4
        TUxQMlE1TjY0SG1tOXoxdHZFdTJYOUkKLS0tIHRFSmFzUHI0REliMUFNQjByZEND
        N1AyZHRBdkxvcEZSb2dUbjVZNEhDNUkK4SGseNvrWgazx0LqHJjR6QmOPVtpGTdj
        S72/YjcjUDHksYRv28FsIjqw3dBGPdfRho9gS47BCTslFHcvHCdx9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T20:52:08Z"
  mac: ENC[AES256_GCM,data:3L8zNyV9v/7j235cnHVW75zZhFY39RcgTQ0Frq+tbOel+imvAmk9ScIJEorg7otDV0sXfLHrw9uCmj2GHlNDOsQTbHZkajWUc1C5w6HGOsmCqOxRiADG+d2QCjJzrsSOxjvHRA/9A7kIgZn3vbT600uRsvODXW2lylVjAbdaKK8=,iv:MlVyVHEhiqKJoOpRE+vet4bVdubwjOYVGgfZDk+/npI=,tag:1UpwiYdkuGsjs5HYgrghtg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
