apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Y3V7r49YKnrNvH9eug2DVnQVZHYpMDObyywlJTloDFc=,iv:SOnU8/gA9R9+zHN/201O5FUf4UQUbsTo/DgXJBTTtE8=,tag:IXwU2PfLpeeIdQii+RPOag==,type:str]
sops:
  age:
    - recipient: age15junp5n3mp3cwtg3kwxz7azea56936aewx4uyjaqlk38dvaq6y5s5r8lr9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndEEwNnM5RDVtTW41eUlu
        dVNVdU5zMmRNR3pPdkRTR3dDd2M2cU9DN3d3CjVwVzA0blp6aXRNbFRhYlMzL3hH
        eGJubmxCRm1kbmhBcnI4dXh5bldrQm8KLS0tIDJ4VDNTRkJvc09pU0tya0JEQmVF
        SlZJdFM0MHdFWVlEc1FmRXZNSk8wRGcK6/PVfT5D6lTqxT2tbAgm2UIn2d2ZmeLK
        hvwH9WcHFr19UYTt0IH9r5cROuWToCtG/gtAFtp7GRzdU+lP+d54xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T20:52:08Z"
  mac: ENC[AES256_GCM,data:86Zr6d7sMAP+iF+A3Mn5PIC8yKGLxMdErmiWNuKHPpllOMfE8yi+EUbiAshirQGUIIMyxV8fOekWP1WnmGlm1MwZBnJYRAwO2Olc533FZrqnkNVDgnuwv17smF2cfwfdfCXzMEvVNjFebfuy4gAsKWXjH8oh430QAbJ2rYm4OkE=,iv:WSUeWfq2HcXr4Q9V9m4NC50rkRvR9VTXhPATxJfuAoo=,tag:uGMYidA7tt8zWbPA3Hy5Ug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
