apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:sqh8vpqqzpeItjP3+SRtTupEIvzqgTn6JYyF+LOdzjv6th6j/W3VerYF1f6o3xKefw36ySL+KXp94owjaAdY8cJt9kZK6Mwf8AZzbxjTakhaMNE5IR3wYAMi4x7g0ofKZZHYOFbd2IvWkBJLbhW1ZUyKPDi38uDlaOHhMAs+lwVPZIfdaZZK3M0sDQyxT5iJxUuyuuHuZdfaXlm99KRQFjZcyDlLm2eR1TlrTLxdBXr59ALI,iv:Q7f3xSt11QLu0gp6pWP5FBTu6+Qyf+1sg2uE7rp4uF0=,tag:qpKnm16i14P0VWwVIu2Org==,type:str]
sops:
  age:
    - recipient: age15junp5n3mp3cwtg3kwxz7azea56936aewx4uyjaqlk38dvaq6y5s5r8lr9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZGppTW10eUhxT0kzZFMy
        ODlwQ1lmbWVFZmtsTC9sNkRxbVRBaU1FcEJrCnNOZjBCLzNSV1BERUN4aytkMGVz
        Tzk5TkJDdEp1a3FhUjY1RkN6MGZTMnMKLS0tIDlSbjBTWnJkOTVYYWZwSURsWnBK
        MmFVdVM3Y1o4V2JFZlJpM1ZJMVRxQTAKD+keWsg99GVrBSpTbpkLz2IhntRRrFOa
        YYyzxNEh18a+Yrm7YWvZckqaFY2gCgvRyuxs36HN0lUD1kn5BBEUmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T20:52:08Z"
  mac: ENC[AES256_GCM,data:SlEYFMrZSX8gs9IegF39p1XcrIu8pImoNn3ziypUbrbEbvtjK0TDWt8XNdu8LsmRvdxcq/phO4TgvzAocDLi+EYxjDG5ugIyhL0RxHuqeO1rVw76V7rP34LWErulSzgj1VuNDDNDubQ3Bejv7cm7xMlg7cxJE7c7lpRQ8wNfQNM=,iv:mVbEOyGwwOAUEtxYzAuRiHYh3eTLbjWu9ibbUfTuueo=,tag:yIRB8fIYIhmBXpIaTNj8Yw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
