apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:8eK8xeypJXn8qwi0BrzxkzQbgksPJVO1vJc1no7Lga/QW1Wb05SFpA==,iv:fFgjBmPW/ZhByoO+AfMKinhSx2fV0sBZGaX5anms6co=,tag:UABT+Viis9wgrmVVqJxIoQ==,type:str]
sops:
  age:
    - recipient: age15junp5n3mp3cwtg3kwxz7azea56936aewx4uyjaqlk38dvaq6y5s5r8lr9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eFViZUFFY1RlKzFTRTRX
        NlRNNHhFMkJqNnN6TEdZeEkvTGdNK3c5LzEwCmw1YlUwbkkvK0NTQWROb0MzZ1Vq
        MWZHSEt4THFwNkFsc29UektWWHAySWcKLS0tIGF2MDJNamVnQUc0MVhMbFZvZ1Ra
        eHdvWVZjbmlvL0lIOVI5My9zV0lwamcKf4IAFVbiDqxICKjH9BfvDPX8r701TH/g
        ZLhVHyp1WgRhKB/8N6nMLvYAlUSsmc9eD0rQvJpOTIQw2R9tOHJ12w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T20:52:08Z"
  mac: ENC[AES256_GCM,data:9ymcjhHUVJJ8PzKI28l6xvTC8QADxlAYF8ssgePMnT79kdTMOIkcBILn08zMUbR5xb70kTO60D3Dwyuw2oKgfogEcVkzhwZ385vJktbqq1msoXRbHsjq2/W6twYAjaHahfqXnrukv/jfTctaM5yUccu8TIT7NAB5sjkgEoTfvoM=,iv:CsTghGfaEoMLL0xD9TyYuCxcCjldP3wAWddZn6PQx00=,tag:Ghk2c0WQQ3QqdgOE1aMkbQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
